# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage_newscroll.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        self.bgpolos = QtWidgets.QLabel(Form)
        self.bgpolos.setGeometry(QtCore.QRect(0, 139, 1920, 941))
        self.bgpolos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bgpolos.setText("")
        self.bgpolos.setObjectName("bgpolos")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1345, 60, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Epilogue SemiBold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"color: white;\n"
"font: 63 12pt \"Epilogue SemiBold\";\n"
"text-align:right;\n"
"}")
        self.label.setObjectName("label")
        self.profil = QtWidgets.QPushButton(Form)
        self.profil.setGeometry(QtCore.QRect(1620, 55, 50, 50))
        self.profil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profil.setStyleSheet("border-image: url(:/images/img/pp_profil.png);")
        self.profil.setText("")
        self.profil.setObjectName("profil")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 129, 1920, 1100))
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"background:transparent;\n"
"border:none;}\n"
"\n"
"            }\n"
"            QScrollBar:vertical {\n"
"                background:transparent;\n"
"                width: 15px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
";\n"
";\n"
"    background-color: rgb(213, 224, 240);\n"
"                min-height: 20px;\n"
"                border-radius: 7px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                border: none;\n"
"                background:transparent;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background:transparent;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 8px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #bfbfbf;\n"
"                min-width: 20px;\n"
"                border-radius: 4px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                border: none;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: none;")
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -1958, 1936, 3050))
        self.scrollAreaWidgetContents.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 2000))
        self.frame.setStyleSheet("background: none")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.ads1_dummy_button = QtWidgets.QPushButton(self.frame)
        self.ads1_dummy_button.setGeometry(QtCore.QRect(240, 306, 621, 336))
        self.ads1_dummy_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ads1_dummy_button.setStyleSheet("QPushButton#ads1_dummy_button{\n"
"background-color: rgba(0, 0, 0, 70);\n"
"padding: 0px 20px;\n"
"border-radius: 32px;\n"
"}\n"
"\n"
"QPushButton#ads1_dummy_button:pressed{\n"
"background-color: rgba(0, 0, 0, 30);\n"
"}\n"
"\n"
"")
        self.ads1_dummy_button.setText("")
        self.ads1_dummy_button.setObjectName("ads1_dummy_button")
        self.ads1 = QtWidgets.QLabel(self.frame)
        self.ads1.setGeometry(QtCore.QRect(240, 305, 621, 341))
        self.ads1.setStyleSheet("image: url(:/images/img/ads1.png);")
        self.ads1.setText("")
        self.ads1.setObjectName("ads1")
        self.ads2 = QtWidgets.QLabel(self.frame)
        self.ads2.setGeometry(QtCore.QRect(880, 306, 777, 341))
        self.ads2.setStyleSheet("image: url(:/images/img/ads2.png);")
        self.ads2.setText("")
        self.ads2.setObjectName("ads2")
        self.ads2_dummy_button = QtWidgets.QPushButton(self.frame)
        self.ads2_dummy_button.setGeometry(QtCore.QRect(880, 306, 776, 338))
        self.ads2_dummy_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ads2_dummy_button.setStyleSheet("QPushButton#ads2_dummy_button{\n"
"background-color: rgba(0, 0, 0, 70);\n"
"padding: 0px 20px;\n"
"border-radius: 32px;\n"
"}\n"
"\n"
"QPushButton#ads2_dummy_button:pressed{\n"
"background-color: rgba(0, 0, 0, 30);\n"
"}\n"
"\n"
"")
        self.ads2_dummy_button.setText("")
        self.ads2_dummy_button.setObjectName("ads2_dummy_button")
        self.jadwal_judul = QtWidgets.QLabel(self.frame)
        self.jadwal_judul.setGeometry(QtCore.QRect(720, 20, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Epilogue")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.jadwal_judul.setFont(font)
        self.jadwal_judul.setStyleSheet("border-image: url(:/images/img/text_atas.png);")
        self.jadwal_judul.setText("")
        self.jadwal_judul.setAlignment(QtCore.Qt.AlignCenter)
        self.jadwal_judul.setObjectName("jadwal_judul")
        self.jadwal_border = QtWidgets.QLabel(self.frame)
        self.jadwal_border.setGeometry(QtCore.QRect(239, 750, 1419, 671))
        self.jadwal_border.setStyleSheet("background-color: rgb(225, 236, 254);\n"
"border-radius:30px;")
        self.jadwal_border.setText("")
        self.jadwal_border.setObjectName("jadwal_border")
        self.jadwal = QtWidgets.QLabel(self.frame)
        self.jadwal.setGeometry(QtCore.QRect(280, 790, 1339, 591))
        self.jadwal.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.jadwal.setText("")
        self.jadwal.setObjectName("jadwal")
        self.tujuan = QtWidgets.QComboBox(self.frame)
        self.tujuan.setGeometry(QtCore.QRect(733, 136, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Epilogue")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tujuan.setFont(font)
        self.tujuan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tujuan.setStyleSheet("/*style for the QComboBox*/\n"
"#tujuan{\n"
"    border-radius:20px;\n"
"\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"#tujuan::drop-down{\n"
"    border:0px;\n"
"}\n"
"\n"
"#tujuan:down-arrow{\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    margin-right: 15px\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView{\n"
"border:none;\n"
"background-color: rgb(255, 255, 255);}")
        self.tujuan.setObjectName("tujuan")
        self.tujuan.addItem("")
        self.tujuan.addItem("")
        self.tujuan.addItem("")
        self.tujuan.addItem("")
        self.cari = QtWidgets.QPushButton(self.frame)
        self.cari.setGeometry(QtCore.QRect(1416, 90, 218, 114))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cari.setFont(font)
        self.cari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cari.setStyleSheet("QPushButton#cari{\n"
"background-color: #2abaa1;\n"
"color: rgb(255, 255, 255);\n"
"padding: 0px 20px;\n"
"border-radius: 32px;\n"
"}\n"
"\n"
"QPushButton#cari:pressed{\n"
"background-color: #219a85;\n"
"}\n"
"\n"
"")
        self.cari.setObjectName("cari")
        self.platform = QtWidgets.QLabel(self.frame)
        self.platform.setGeometry(QtCore.QRect(240, 72, 1420, 149))
        self.platform.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(213, 213, 213);\n"
"border-radius:40px;\n"
"border : none;")
        self.platform.setText("")
        self.platform.setObjectName("platform")
        self.bgtujuan = QtWidgets.QLabel(self.frame)
        self.bgtujuan.setGeometry(QtCore.QRect(650, 76, 361, 140))
        self.bgtujuan.setStyleSheet("image: url(:/images/img/untuk tujuan.png);")
        self.bgtujuan.setText("")
        self.bgtujuan.setObjectName("bgtujuan")
        self.bgberangkat = QtWidgets.QLabel(self.frame)
        self.bgberangkat.setGeometry(QtCore.QRect(262, 76, 361, 140))
        self.bgberangkat.setStyleSheet("image: url(:/images/img/berangkat dari.png);")
        self.bgberangkat.setText("")
        self.bgberangkat.setObjectName("bgberangkat")
        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(1118, 138, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Epilogue")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("QDateEdit {\n"
" border-radius: 2px; border: 0px solid #cccccc; \n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"}\n"
"\n"
"QDateEdit::drop-down { border: none; width: 30px;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
" }\n"
"\n"
"QDateEdit::down-button {border: none; \n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"\n"
"QDateEdit::up-button {border: none; \n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QCalendarWidget {\n"
"        background: transparent;\n"
"    }\n"
"    QCalendarWidget > #dateEdit {\n"
"        /* background for calendar dates */\n"
"        background: rgba(204, 204, 204, 127);\n"
"        /* \n"
"            default background for headers, can be overridden by using\n"
"            QCalendarWidget.setHeaderTextFormat()\n"
"        */\n"
"        alternate-background-color: rgba(127, 127, 127, 127);}")
        self.dateEdit.setReadOnly(False)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.bgtujuan_2 = QtWidgets.QLabel(self.frame)
        self.bgtujuan_2.setGeometry(QtCore.QRect(1030, 76, 361, 140))
        self.bgtujuan_2.setStyleSheet("image: url(:/images/img/tanggal berangkat.png);")
        self.bgtujuan_2.setText("")
        self.bgtujuan_2.setObjectName("bgtujuan_2")
        self.berangkat = QtWidgets.QComboBox(self.frame)
        self.berangkat.setGeometry(QtCore.QRect(345, 136, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Epilogue")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.berangkat.setFont(font)
        self.berangkat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.berangkat.setStyleSheet("/*style for the QComboBox*/\n"
"#berangkat{\n"
"    border-radius:20px;\n"
"\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"#berangkat::drop-down{\n"
"    border:0px;\n"
"}\n"
"\n"
"#berangkat:down-arrow{\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    margin-right: 15px\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"border:none;\n"
"background-color: rgb(255, 255, 255);}\n"
"")
        self.berangkat.setInputMethodHints(QtCore.Qt.ImhNone)
        self.berangkat.setDuplicatesEnabled(False)
        self.berangkat.setObjectName("berangkat")
        self.berangkat.addItem("")
        self.berangkat.addItem("")
        self.berangkat.addItem("")
        self.berangkat.addItem("")
        self.text_jadwal_minggu_ini = QtWidgets.QLabel(self.frame)
        self.text_jadwal_minggu_ini.setGeometry(QtCore.QRect(239, 670, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Epilogue ExtraBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.text_jadwal_minggu_ini.setFont(font)
        self.text_jadwal_minggu_ini.setObjectName("text_jadwal_minggu_ini")
        self.bg_scroll = QtWidgets.QLabel(self.frame)
        self.bg_scroll.setEnabled(True)
        self.bg_scroll.setGeometry(QtCore.QRect(0, -150, 1920, 436))
        self.bg_scroll.setStyleSheet("image: url(:/images/img/atas.png);")
        self.bg_scroll.setText("")
        self.bg_scroll.setObjectName("bg_scroll")
        self.ads3_perjalanan = QtWidgets.QLabel(self.frame)
        self.ads3_perjalanan.setGeometry(QtCore.QRect(240, 1540, 1421, 601))
        self.ads3_perjalanan.setStyleSheet("image: url(:/images/img/ads3.png);")
        self.ads3_perjalanan.setText("")
        self.ads3_perjalanan.setObjectName("ads3_perjalanan")
        self.judul_perjalanan_anda = QtWidgets.QLabel(self.frame)
        self.judul_perjalanan_anda.setGeometry(QtCore.QRect(240, 1460, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Epilogue ExtraBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.judul_perjalanan_anda.setFont(font)
        self.judul_perjalanan_anda.setObjectName("judul_perjalanan_anda")
        self.ads4_review = QtWidgets.QLabel(self.frame)
        self.ads4_review.setGeometry(QtCore.QRect(240, 2180, 1421, 361))
        self.ads4_review.setStyleSheet("image: url(:/images/img/review_home.png);")
        self.ads4_review.setText("")
        self.ads4_review.setObjectName("ads4_review")
        self.ads5_about = QtWidgets.QLabel(self.frame)
        self.ads5_about.setGeometry(QtCore.QRect(240, 2610, 1421, 261))
        self.ads5_about.setStyleSheet("image: url(:/images/img/about_home.png);")
        self.ads5_about.setText("")
        self.ads5_about.setObjectName("ads5_about")
        self.jadwal_pandas = QtWidgets.QTableWidget(self.frame)
        self.jadwal_pandas.setGeometry(QtCore.QRect(320, 820, 1271, 531))
        self.jadwal_pandas.setStyleSheet("border:none")
        self.jadwal_pandas.setObjectName("jadwal_pandas")
        self.jadwal_pandas.setColumnCount(0)
        self.jadwal_pandas.setRowCount(0)
        self.copyright_kotak = QtWidgets.QLabel(self.frame)
        self.copyright_kotak.setGeometry(QtCore.QRect(-10, 2809, 1921, 101))
        self.copyright_kotak.setStyleSheet("background-color: rgb(242, 247, 254);")
        self.copyright_kotak.setText("")
        self.copyright_kotak.setObjectName("copyright_kotak")
        self.bg_scroll.raise_()
        self.ads1.raise_()
        self.ads2.raise_()
        self.ads1_dummy_button.raise_()
        self.ads2_dummy_button.raise_()
        self.jadwal_judul.raise_()
        self.jadwal_border.raise_()
        self.jadwal.raise_()
        self.platform.raise_()
        self.bgtujuan_2.raise_()
        self.cari.raise_()
        self.bgtujuan.raise_()
        self.bgberangkat.raise_()
        self.dateEdit.raise_()
        self.berangkat.raise_()
        self.tujuan.raise_()
        self.text_jadwal_minggu_ini.raise_()
        self.ads3_perjalanan.raise_()
        self.judul_perjalanan_anda.raise_()
        self.ads4_review.raise_()
        self.jadwal_pandas.raise_()
        self.copyright_kotak.raise_()
        self.ads5_about.raise_()
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.bg_nutupi_scroll = QtWidgets.QLabel(Form)
        self.bg_nutupi_scroll.setEnabled(True)
        self.bg_nutupi_scroll.setGeometry(QtCore.QRect(0, 0, 1920, 142))
        self.bg_nutupi_scroll.setStyleSheet("image: url(:/images/img/atas_scroll.png);")
        self.bg_nutupi_scroll.setText("")
        self.bg_nutupi_scroll.setObjectName("bg_nutupi_scroll")
        self.bgpolos.raise_()
        self.scrollArea.raise_()
        self.bg_nutupi_scroll.raise_()
        self.label.raise_()
        self.profil.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "User"))
        self.tujuan.setItemText(0, _translate("Form", "Jakarta"))
        self.tujuan.setItemText(1, _translate("Form", "Bali"))
        self.tujuan.setItemText(2, _translate("Form", "Semarang"))
        self.tujuan.setItemText(3, _translate("Form", "Solo"))
        self.cari.setText(_translate("Form", "Cari"))
        self.berangkat.setItemText(0, _translate("Form", "Jakarta"))
        self.berangkat.setItemText(1, _translate("Form", "Bali"))
        self.berangkat.setItemText(2, _translate("Form", "Semarang"))
        self.berangkat.setItemText(3, _translate("Form", "Solo"))
        self.text_jadwal_minggu_ini.setText(_translate("Form", "Jadwal Minggu Ini"))
        self.judul_perjalanan_anda.setText(_translate("Form", "Perjalanan Anda"))
import res_home_rc
